version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "platform_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  back: 
    container_name: back_django
    build: 
      dockerfile: ./back/Dockerfile
    command: python manage.py runserver
    volumes:
      - ./back:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  front:
    image: daniildzheparov/front_app:v1
    volumes:
      - ./front:/my_project
    ports:
      - 8087:80
    expose:
      - 8087 