version: "3.7"
services:
  ch_server:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: "clch_db"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "default"
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
        - platform

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
        - platform

networks:
  platform: