version: "3.7"
services:
  postgres_dp:
    image: postgres
    environment:
      POSTGRES_DB: "platform_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - platform

  ch_server:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: "clch_db"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "default"
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
        - platform

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
        - platform

networks:
  platform: