# Generated by Django 4.1.3 on 2022-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklogs',
            fields=[
                ('WorklogId', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=500)),
                ('Employee', models.CharField(max_length=500)),
                ('WorklogHours', models.CharField(max_length=500)),
            ],
        ),
    ]
